### PR TITLE
Add Rust module output

### PR DESCRIPTION
**Pull request by wez**
This commit adds a template for a Rust module that provides equivalent
functionality to the C++ implementation.

`make rust` will verify the syntax and run the handful of very basic
tests; since the tables and logic are the same as those used by the C++
implementation, the Rust tests are really just there to sniff test that
the binary search is working for a few inputs.

### CODE REVIEW

**Comment by wez** [comment]
I plan to use this to reconcile https://github.com/wez/wezterm/issues/1231

**Comment by ridiculousfish** [comment]
Hi wez 👋 overjoyed to have Rust support, I expect to merge on Friday after Thanksgiving!

**Comment by ridiculousfish** [comment]
Looks great, thank you. Did you want this to be published as a crate, or will you just copy the generated file directly into wezterm?

**Comment by wez** [comment]
I copied the generated file directly, so I'm OK.  I think there are folks in the community that would welcome an official crate if you're feeling up for it!

**Pull request merged**
