### PR TITLE
Update: use later version of emoji-data.txt

### PR DESCRIPTION
**Pull request by SlySven**
I needed to tweak the `generate.py` script that read the part of the comment that contains the Unicode version of when a glyph was introduced. Some entries in the newer version of the `emoji-data.txt` file are for reserved CodePoints and the version entry of `NA` was breaking at the point in the script that was expecting a floating point number. For those we `return` a version of `0.0` instead and then ignore them.

I also had to comment out the test code in the Makefile as the alternative that was being tested against was using Unicode 9.0 data and is not longer comparable as we are now at Unicode 12. Hopefully the revised script should be compatible with later versions of the data from the Unicode people when it emerges.

This should close https://github.com/ridiculousfish/widecharwidth/issues/5 .

Signed-off-by: Stephen Lyons <slysven@virginmedia.com>

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Thanks for taking this on! However I would not expect `widechar_widened_table` to be modified by this - the set of characters that were widened in Unicode 9 should not be changed by newer Unicode versions.

**Comment by ridiculousfish** [comment]
Unicode < 9 said nothing about emoji widths, so they were rendered as width 1. Unicode 9 added the requirement "emoji presentation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value".  So the width of an emoji depends on whether the implementation is using Unicode 8 or Unicode 9 (unless that emoji was actually introduced in Unicode 9 or later)

**Comment by vadi2** [comment]
That's great to know, thanks!

**Comment by vadi2** [comment]
@SlySven so what's the status of this then?

**Comment by faho** [comment]
Merged as 5b7e917. Terribly sorry for the delay!

>However I would not expect widechar_widened_table to be modified by this

So the problem is apparently that the *classification* of some characters changed, they were made emoji retroactively. That's not something widewcharwidth is prepared for, but that's also something we can add later, as the problem exists whether or not we update the emoji data - which doesn't contain this information, so we'd have to parse multiple versions and figure out the differences.

**Comment by data-man** [comment]
The current version is now 13.0.
I propose change links to:
```
UNICODE_DATA_URL = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"
EAW_URL = "https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt"
EMOJI_DATA_URL = "https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt"
```

**Comment by faho** [comment]
> I propose change links to:

Yeah, no, because the format changed again. Since they tend to do that, adding the "latest" qualifier just means the script *breaks* whenever that happens instead of chugging along with the old version.

**Comment by thefallentree** [comment]
iits best to keep same release cycle with the spec, because not everyone
will need latest spec (it needs to be synced to the terminal or media that
displays it)

**Pull request closed without merging**
